#!/bin/bash
# 重置磁力計參數到正常狀態
# 在 MAVProxy (SITL 視窗) 中執行這些指令

echo "=============================================="
echo "  重置磁力計參數到正常狀態"
echo "=============================================="
echo ""
echo "請在 MAVProxy (tmux window 1) 中執行以下指令:"
echo ""
echo "# 1. 重置馬達干擾參數"
echo "param set SIM_MAG_MOT_X 0"
echo "param set SIM_MAG_MOT_Y 0"
echo "param set SIM_MAG_MOT_Z 0"
echo ""
echo "# 2. 重置磁力計縮放"
echo "param set SIM_MAG1_SCALING 1.0"
echo "param set SIM_MAG2_SCALING 1.0"
echo "param set SIM_MAG3_SCALING 1.0"
echo ""
echo "# 3. 重置磁力計偏移"
echo "param set SIM_MAG1_OFS_X 0"
echo "param set SIM_MAG1_OFS_Y 0"
echo "param set SIM_MAG1_OFS_Z 0"
echo ""
echo "# 4. 重置磁場異常"
echo "param set SIM_MAG_ALY_X 0"
echo "param set SIM_MAG_ALY_Y 0"
echo "param set SIM_MAG_ALY_Z 0"
echo ""
echo "# 5. 確保磁力計未設定為故障"
echo "param set SIM_MAG1_FAIL 0"
echo "param set SIM_MAG2_FAIL 0"
echo "param set SIM_MAG3_FAIL 0"
echo ""
echo "# 6. 重置磁力計噪音"
echo "param set SIM_MAG_RND 0"
echo ""
echo "# 7. 保存參數 (可選)"
echo "param save"
echo ""
echo "=============================================="
echo "✅ 完成後,重新解鎖應該就正常了"
echo "=============================================="
