#!/bin/bash
# 簡易版磁力計干擾模擬 (使用 MAVProxy 指令)
# 適合快速測試,不需要額外 Python 程式

echo "=============================================="
echo "  磁力計干擾模擬 - MAVProxy 腳本版本"
echo "=============================================="
echo ""
echo "此腳本會在 MAVProxy 中執行一系列指令"
echo "模擬磁力計逐漸受到干擾的過程"
echo ""
echo "使用方法:"
echo "  1. 確保 SITL 已啟動並進入 MAVProxy"
echo "  2. 在 MAVProxy 中執行: script ./simulate_compass_simple.sh"
echo ""
echo "或者手動複製以下指令到 MAVProxy:"
echo ""
echo "=============================================="
echo "Phase 1: 正常狀態 (10秒)"
echo "=============================================="
echo "param set SIM_MAG_MOT_X 0"
echo "param set SIM_MAG_MOT_Y 0"
echo "param set SIM_MAG_MOT_Z 0"
echo "param set SIM_MAG1_SCALING 0.75"
echo ""
echo "等待 10 秒後,執行 Phase 2..."
echo ""
echo "=============================================="
echo "Phase 2: 輕度干擾 (磁場強度 1.2x)"
echo "=============================================="
echo "param set SIM_MAG_MOT_X 1000"
echo "param set SIM_MAG_MOT_Y 800"
echo "param set SIM_MAG_MOT_Z 1200"
echo "param set SIM_MAG1_SCALING 1.0"
echo ""
echo "等待 5 秒後,執行 Phase 3..."
echo ""
echo "=============================================="
echo "Phase 3: 中度干擾 (磁場強度 1.5x)"
echo "=============================================="
echo "param set SIM_MAG_MOT_X 2000"
echo "param set SIM_MAG_MOT_Y 1600"
echo "param set SIM_MAG_MOT_Z 2400"
echo "param set SIM_MAG1_SCALING 1.2"
echo ""
echo "等待 5 秒後,執行 Phase 4..."
echo ""
echo "=============================================="
echo "Phase 4: 嚴重干擾 (磁場強度 2.0x)"
echo "=============================================="
echo "param set SIM_MAG_MOT_X 4000"
echo "param set SIM_MAG_MOT_Y 3200"
echo "param set SIM_MAG_MOT_Z 4800"
echo "param set SIM_MAG1_SCALING 1.5"
echo ""
echo "⚠️  預期: Compass Unhealthy 警告"
echo "⚠️  建議: 切換到 STABILIZE 模式"
echo ""
echo "等待 10 秒後,執行 Phase 5..."
echo ""
echo "=============================================="
echo "Phase 5: 恢復正常"
echo "=============================================="
echo "param set SIM_MAG_MOT_X 0"
echo "param set SIM_MAG_MOT_Y 0"
echo "param set SIM_MAG_MOT_Z 0"
echo "param set SIM_MAG1_SCALING 1.0"
echo ""
echo "=============================================="
echo "✅ 模擬完成"
echo "=============================================="
